import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import { Roboto as FontSans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import BackToTop from "@/components/BackToTop";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const fontSans = FontSans({
  subsets: ["cyrillic"],
  weight: ["100", "300", "400", "500", "700"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-background", fontSans.className)}>
        <Navbar />
        <BackToTop />
        {children}
      </body>
    </html>
  );
}
